/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Control.AccountControl;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import Model.Account;
import Model.Customer;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.*;
import javax.swing.*;
import View.FormCustomer;

/**
 *
 * @author Hi
 */
public class FormLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLogin.class.getName());

    /**
     * Creates new form FormLogin
     */
    private AccountControl controller;
    private boolean isOpenEye1 = true, isOpenEye2 = true;
    private ImageIcon openEyeImage = new javax.swing.ImageIcon(getClass().getResource("/MyImage/seenEye.png"));
    private ImageIcon closeEyeImage = new javax.swing.ImageIcon(getClass().getResource("/MyImage/hideEye.png"));
    private CardLayout cardLayout;
    public FormLogin() {
        try {
            FlatLightLaf.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        controller = new AccountControl(this);
        initComponents();
        // txtPassword1.setEchoChar((char) 0);
        // txtPassword2.setEchoChar((char) 0); 
        cardLayout = (CardLayout) pnlCardBegin.getLayout();
        this.setLocationRelativeTo(null);
        setFormRegister();
        setRoundButton();
        btEyePass1.doClick(); btEyePass2.doClick();
        setVisible(true);
    }
    public void setRoundButton(){
        
        btCreateAcc.putClientProperty(FlatClientProperties.STYLE,"arc:25; ");
        btLogin1.putClientProperty(FlatClientProperties.STYLE,"arc:25; ");
        btRegister2.putClientProperty(FlatClientProperties.STYLE,"arc:25; ");
        
        txtEmail1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        txtPassword1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        txtEmail2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        txtPassword2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        txtFullName2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        txtConfirmPass2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        fieldDay2.putClientProperty("FlatLaf.style", "borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        fieldMonth2.putClientProperty("FlatLaf.style", "borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        fieldYear2.putClientProperty("FlatLaf.style", "borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
    }
    public void setFormRegister(){
        FlatIntelliJLaf.setup();

    }
    private void resetPartLogin(){
        JTextField[] arr = {txtEmail1, txtPassword1};
        for(JTextField x : arr){
            x.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }
    private void resetPartRegister(){
        JTextField[] arr = {txtEmail2, txtPassword2, txtFullName2, txtConfirmPass2};
        for(JTextField x : arr){
            x.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupSex = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pnlCardBegin = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btEyePass1 = new javax.swing.JButton();
        txtPassword1 = new javax.swing.JPasswordField();
        btLogin1 = new javax.swing.JButton();
        btForgotPass = new javax.swing.JButton();
        btCreateAcc = new javax.swing.JButton();
        lblWarn1 = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFullName2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtConfirmPass2 = new javax.swing.JPasswordField();
        btEyePass2 = new javax.swing.JButton();
        btRegister2 = new javax.swing.JButton();
        fieldDay2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        fieldMonth2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldYear2 = new javax.swing.JComboBox<>();
        btMale2 = new javax.swing.JRadioButton();
        btFemale2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        btLogin2 = new javax.swing.JButton();
        lblWarn2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(178, 137, 145));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/newNau1.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);

        pnlCardBegin.setLayout(new java.awt.CardLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 137, 145));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(178, 137, 145));
        jLabel4.setText("Email");

        txtEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmail1FocusLost(evt);
            }
        });
        txtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 137, 145));
        jLabel5.setText("Password");

        btEyePass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/hideEye.png"))); // NOI18N
        btEyePass1.setContentAreaFilled(false);
        btEyePass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEyePass1ActionPerformed(evt);
            }
        });

        txtPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassword1FocusLost(evt);
            }
        });

        btLogin1.setBackground(new java.awt.Color(153, 255, 255));
        btLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLogin1.setForeground(new java.awt.Color(178, 137, 145));
        btLogin1.setText("Login");
        btLogin1.setFocusPainted(false);
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });

        btForgotPass.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btForgotPass.setForeground(new java.awt.Color(178, 137, 145));
        btForgotPass.setText("Forgot Password?");
        btForgotPass.setContentAreaFilled(false);
        btForgotPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btForgotPass.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btCreateAcc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCreateAcc.setForeground(new java.awt.Color(178, 137, 145));
        btCreateAcc.setText("Create Account");
        btCreateAcc.setContentAreaFilled(false);
        btCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateAccActionPerformed(evt);
            }
        });

        lblWarn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWarn1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btCreateAcc))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblWarn1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btForgotPass))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtPassword1)
                                    .addComponent(btLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEyePass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(103, 103, 103)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEyePass1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWarn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btForgotPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pnlCardBegin.add(pnlLogin, "cardLogin");

        pnlRegister.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 137, 145));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTER");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 137, 145));
        jLabel7.setText("Fullname");

        txtFullName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullName2FocusLost(evt);
            }
        });
        txtFullName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullName2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(178, 137, 145));
        jLabel8.setText("Email");

        txtEmail2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmail2FocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(178, 137, 145));
        jLabel9.setText("Password");

        txtPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassword2FocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(178, 137, 145));
        jLabel10.setText("Confirm Password");

        txtConfirmPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPass2FocusLost(evt);
            }
        });

        btEyePass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImage/hideEye.png"))); // NOI18N
        btEyePass2.setContentAreaFilled(false);
        btEyePass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEyePass2ActionPerformed(evt);
            }
        });

        btRegister2.setBackground(new java.awt.Color(153, 255, 255));
        btRegister2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRegister2.setForeground(new java.awt.Color(178, 137, 145));
        btRegister2.setText("Register");
        btRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegister2ActionPerformed(evt);
            }
        });

        fieldDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        fieldDay2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldDay2FocusLost(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(178, 137, 145));
        jLabel11.setText("Day");

        fieldMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        fieldMonth2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldMonth2FocusLost(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(178, 137, 145));
        jLabel12.setText("Month");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(178, 137, 145));
        jLabel13.setText("Year");

        fieldYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        fieldYear2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldYear2FocusLost(evt);
            }
        });

        btGroupSex.add(btMale2);
        btMale2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btMale2.setForeground(new java.awt.Color(178, 137, 145));
        btMale2.setSelected(true);
        btMale2.setText("Male");

        btGroupSex.add(btFemale2);
        btFemale2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFemale2.setForeground(new java.awt.Color(178, 137, 145));
        btFemale2.setText("Female");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(178, 137, 145));
        jLabel14.setText("Gender");

        btLogin2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btLogin2.setForeground(new java.awt.Color(178, 137, 145));
        btLogin2.setText("Have Account? Login");
        btLogin2.setContentAreaFilled(false);
        btLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin2ActionPerformed(evt);
            }
        });

        lblWarn2.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLogin2)
                .addGap(45, 45, 45))
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEyePass2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(txtFullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegisterLayout.createSequentialGroup()
                            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btMale2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlRegisterLayout.createSequentialGroup()
                                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlRegisterLayout.createSequentialGroup()
                                    .addComponent(btFemale2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblWarn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConfirmPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(btRegister2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMale2)
                    .addComponent(btFemale2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEyePass2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarn2, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fieldYear2.setSelectedIndex(105);

        pnlCardBegin.add(pnlRegister, "cardRegister");

        jPanel1.setBackground(new java.awt.Color(178, 137, 145));

        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("WELCOME TO OUR BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlCardBegin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1))
            .addComponent(pnlCardBegin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1ActionPerformed

    private void btEyePass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEyePass1ActionPerformed
        // TODO add your handling code here:
        if(isOpenEye1){
            txtPassword1.setEchoChar('•');
            btEyePass1.setIcon(closeEyeImage);
            isOpenEye1 = false;
        }
        else{
            txtPassword1.setEchoChar((char) 0);
            btEyePass1.setIcon(openEyeImage);
            isOpenEye1 = true;
        }
    }//GEN-LAST:event_btEyePass1ActionPerformed

    private void btCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateAccActionPerformed
        // TODO add your handling code here:
        resetPartRegister();
        cardLayout.show(pnlCardBegin, "cardRegister");
    }//GEN-LAST:event_btCreateAccActionPerformed

    private void btEyePass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEyePass2ActionPerformed
        // TODO add your handling code here:
        if(isOpenEye2){
            txtPassword2.setEchoChar('•');
            btEyePass2.setIcon(closeEyeImage);
            isOpenEye2 = false;
        }
        else{
            txtPassword2.setEchoChar((char) 0);
            btEyePass2.setIcon(openEyeImage);
            isOpenEye2 = true;
        }
    }//GEN-LAST:event_btEyePass2ActionPerformed

    private void btRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegister2ActionPerformed
        // TODO add your handling code here:
        lblWarn2.setText("");
        String pass = txtPassword2.getText().trim(), confirmPass = txtConfirmPass2.getText().trim();
        String fullName = txtFullName2.getText().trim(), email = txtEmail2.getText().trim();
        String gender = "Male"; if(btFemale2.isSelected()) gender = "Female";
        String day = fieldDay2.getSelectedItem().toString() + "/"
                + fieldMonth2.getSelectedItem().toString() + "/"
                + fieldYear2.getSelectedItem().toString(); 
        LocalDate birthDay = LocalDate.parse(day, DateTimeFormatter.ofPattern("d/M/yyyy"));
        String emailRegex = "^[A-Za-z0-9]+([._%+\\-][A-Za-z0-9]+)*@"
                  + "[A-Za-z0-9](?:[A-Za-z0-9\\-]{0,61}[A-Za-z0-9])?"
                  + "(?:\\.[A-Za-z0-9](?:[A-Za-z0-9\\-]{0,61}[A-Za-z0-9])?)+$";
        if(fullName.isEmpty()){
            txtFullName2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        if(email.isEmpty()){
            txtEmail2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        if(!email.matches(emailRegex)){
            lblWarn2.setText("Invalid email address");
            return;
        }
        if(pass.length() < 6){
            lblWarn2.setText("Password must be at least 6 characters long");
            return;
        }
        if(pass.isEmpty()){
            txtPassword2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        if(confirmPass.isEmpty()){
            txtConfirmPass2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        if(!pass.equals(confirmPass)){
            lblWarn2.setText("Password does not match");
            return;
        }
        Account x = controller.getAccountByEmail(email);
        if(x != null){
            if(x.isActive()) lblWarn2.setText("Account already exists");
            else{
                JOptionPane.showMessageDialog(this, "Account is blocked!", "", JOptionPane.WARNING_MESSAGE);
            }
            return;
        }
        if(!new OTPDialog(this, email, "xác thực tài khoản").isMatch()){
            return;
        }
        Account ac = new Customer(fullName, email, pass, gender, birthDay, true , (long)0);
        controller.addAccount(ac);
        JOptionPane.showMessageDialog(this, "Register completely", "", JOptionPane.INFORMATION_MESSAGE);
        cardLayout.show(pnlCardBegin, "cardLogin");
    }//GEN-LAST:event_btRegister2ActionPerformed

    private void btLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin2ActionPerformed
        // TODO add your handling code here:
        resetPartLogin();
        cardLayout.show(pnlCardBegin, "cardLogin");
    }//GEN-LAST:event_btLogin2ActionPerformed

    private void txtFullName2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullName2FocusLost
        // TODO add your handling code here:
        txtFullName2.setText(txtFullName2.getText().trim().toUpperCase());
        if(txtFullName2.getText().isEmpty()){
            txtFullName2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtFullName2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtFullName2FocusLost

    private void txtEmail2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail2FocusLost
        // TODO add your handling code here:
        txtEmail2.setText(txtEmail2.getText().trim());
        if(txtEmail2.getText().isEmpty()){
            txtEmail2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtEmail2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtEmail2FocusLost

    private void txtPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusLost
        // TODO add your handling code here:
        txtPassword2.setText(txtPassword2.getText().trim());
        if(txtPassword2.getText().isEmpty()){
            txtPassword2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtPassword2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtPassword2FocusLost

    private void txtConfirmPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPass2FocusLost
        // TODO add your handling code here:
        txtConfirmPass2.setText(txtConfirmPass2.getText().trim());
        if(txtConfirmPass2.getText().isEmpty()){
            txtConfirmPass2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtConfirmPass2.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtConfirmPass2FocusLost

    private void txtEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail1FocusLost
        // TODO add your handling code here:
        txtEmail1.setText(txtEmail1.getText().trim());
        if(txtEmail1.getText().isEmpty()){
            txtEmail1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtEmail1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtEmail1FocusLost

    private void txtPassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword1FocusLost
        // TODO add your handling code here:
        txtPassword1.setText(txtPassword1.getText().trim());
        if(txtPassword1.getText().isEmpty()){
            txtPassword1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
        else{
            txtPassword1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#B28991; focusedBorderColor:#99FFFF; background:#F0F8FF;");
        }
    }//GEN-LAST:event_txtPassword1FocusLost

    private void fieldDay2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDay2FocusLost
        // TODO add your handling code here:
        String ss = fieldDay2.getSelectedItem().toString() + "/"
                + fieldMonth2.getSelectedItem().toString() + "/"
                + fieldYear2.getSelectedItem().toString(); 
        LocalDate date = LocalDate.parse(ss, DateTimeFormatter.ofPattern("d/M/yyyy"));
        fieldDay2.setSelectedIndex(date.getDayOfMonth() - 1);
        fieldMonth2.setSelectedIndex(date.getMonthValue() - 1);
        fieldYear2.setSelectedIndex(date.getYear() - 1900);
    }//GEN-LAST:event_fieldDay2FocusLost

    private void fieldMonth2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldMonth2FocusLost
        // TODO add your handling code here:
        String ss = fieldDay2.getSelectedItem().toString() + "/"
                + fieldMonth2.getSelectedItem().toString() + "/"
                + fieldYear2.getSelectedItem().toString(); 
        LocalDate date = LocalDate.parse(ss, DateTimeFormatter.ofPattern("d/M/yyyy"));
        fieldDay2.setSelectedIndex(date.getDayOfMonth() - 1);
        fieldMonth2.setSelectedIndex(date.getMonthValue() - 1);
        fieldYear2.setSelectedIndex(date.getYear() - 1900);
    }//GEN-LAST:event_fieldMonth2FocusLost

    private void fieldYear2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldYear2FocusLost
        // TODO add your handling code here:
        String ss = fieldDay2.getSelectedItem().toString() + "/"
                + fieldMonth2.getSelectedItem().toString() + "/"
                + fieldYear2.getSelectedItem().toString(); 
        LocalDate date = LocalDate.parse(ss, DateTimeFormatter.ofPattern("d/M/yyyy"));
        fieldDay2.setSelectedIndex(date.getDayOfMonth() - 1);
        fieldMonth2.setSelectedIndex(date.getMonthValue() - 1);
        fieldYear2.setSelectedIndex(date.getYear() - 1900);
    }//GEN-LAST:event_fieldYear2FocusLost

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        // TODO add your handling code here:
        lblWarn1.setText("");
        String email = txtEmail1.getText(), password = txtPassword1.getText();
        if(email.isEmpty()){
            txtEmail1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        if(password.isEmpty()){
            txtPassword1.putClientProperty("FlatLaf.style", "arc:20; borderColor:#FF3333; focusedBorderColor:#99FFFF; background:#F0F8FF;");
            return;
        }
        Account ac = controller.getAccountByEmail(email);
        if(ac == null || !ac.getPassword().equals(password)){
            lblWarn1.setText("Wrong Email Or Password");
            Timer clearWarning = new Timer(1000, e -> lblWarn1.setText(""));
            clearWarning.setRepeats(false);
            clearWarning.start();
            return;
        }
        if(!ac.isActive()){
            JOptionPane.showMessageDialog(this, "Account is blocked!", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // JOptionPane.showMessageDialog(this, "login successfully", "", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        if(ac.getType().equals("Customer")){
            new FormCustomer(email).setVisible(true);
        }
        else{
            new FormStaff(email).setVisible(true);
        }
    }//GEN-LAST:event_btLogin1ActionPerformed

    private void txtFullName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullName2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLogin());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateAcc;
    private javax.swing.JButton btEyePass1;
    private javax.swing.JButton btEyePass2;
    private javax.swing.JRadioButton btFemale2;
    private javax.swing.JButton btForgotPass;
    private javax.swing.ButtonGroup btGroupSex;
    private javax.swing.JButton btLogin1;
    private javax.swing.JButton btLogin2;
    private javax.swing.JRadioButton btMale2;
    private javax.swing.JButton btRegister2;
    private javax.swing.JComboBox<String> fieldDay2;
    private javax.swing.JComboBox<String> fieldMonth2;
    private javax.swing.JComboBox<String> fieldYear2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWarn1;
    private javax.swing.JLabel lblWarn2;
    private javax.swing.JPanel pnlCardBegin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPasswordField txtConfirmPass2;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtFullName2;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    // End of variables declaration//GEN-END:variables
}
