/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.ui.RectangleEdge;
import org.jfree.chart.ui.RectangleInsets;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Hi
 */
public class TestChart extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestChart.class.getName());

    /**
     * Creates new form TestChart
     */
    public TestChart() {
        initComponents();
        showCircleChart();
        showCategoryChart();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void showCircleChart(){
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Transfer", 10);
        dataset.setValue("Withdraw", 20);
        dataset.setValue("Deposit", 20);
        
        JFreeChart chart = ChartFactory.createPieChart("My Title", dataset, true, true, true);
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setSectionPaint("Transfer", new Color(255, 255, 102));
        plot.setSectionPaint("Withdraw", new Color(102, 255, 102));
        plot.setSectionPaint("Deposit", new Color(255, 102, 153));
        
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator(
            "{2}"    // {0}=tên, {1}=giá trị, {2}=tỉ lệ %
        ));
        plot.setToolTipGenerator(new StandardPieToolTipGenerator(
            "{0}"   // {0}=tên, {1}=giá trị, {2}=tỉ lệ %
        ));
        // plot.setSimpleLabels(true);

// Căn chỉnh vị trí label nằm trong lát
        // plot.setInteriorGap(0.04); // giảm khoảng trống giữa tâm và lát
        plot.setLabelFont(new Font("Arial", Font.BOLD, 12));
        plot.setLabelBackgroundPaint(Color.WHITE);
        plot.setBackgroundPaint(new Color(204, 255, 255));
        // plot.set
        plot.setInteriorGap(0.01);
        ChartPanel chartPnl = new ChartPanel(chart);
        chartPnl.setDisplayToolTips(true);
        chartPnl.setMouseWheelEnabled(true); 
        
        
        pnlCircle.removeAll(); 
        pnlCircle.add(chartPnl, BorderLayout.CENTER);
        pnlCircle.revalidate();
        pnlCircle.repaint();
    }
    
    private void showCategoryChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(12_000_000, "Income", "Tháng 6");
        dataset.addValue(8_000_000, "Expense", "Tháng 6");
        dataset.addValue(15_000_000, "Income", "Tháng 7");
        dataset.addValue(10_000_000, "Withdraw", "Tháng 7");
        dataset.addValue(14_000_000, "Income", "Tháng 8");
        dataset.addValue(7_500_000, "Withdraw", "Tháng 8");
        dataset.addValue(16_000_000, "Income", "Tháng 9");
        dataset.addValue(9_000_000, "Withdraw", "Tháng 9");
        dataset.addValue(13_000_000, "Deposit", "Tháng 10");
        dataset.addValue(8_800_000, "Withdraw", "Tháng 10");

        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê thu/chi 5 tháng gần nhất", // Tiêu đề
                "Tháng",                            // Trục X
                "Số tiền (VNĐ)",                    // Trục Y
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        
        NumberFormat vnFormat = NumberFormat.getInstance(new Locale("vi", "VN"));
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setNumberFormatOverride(vnFormat);
        // Giao diện ban đầu
        plot.setBackgroundPaint(new Color(204,255,255));
        plot.setRangeGridlinePaint(Color.GRAY);
        renderer.setBarPainter(new org.jfree.chart.renderer.category.StandardBarPainter());
        renderer.setSeriesPaint(0, new Color(0, 153, 255));  // Thu
        renderer.setSeriesPaint(1, new Color(255, 102, 102)); // Chi

       
        plot.getDomainAxis().setCategoryMargin(0.3);
        renderer.setItemMargin(0.0); 

        renderer.setDefaultToolTipGenerator(
            new StandardCategoryToolTipGenerator("({0}, {1}) = {2} ", NumberFormat.getInstance(new Locale("vi", "VN")))
        );
       
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(800, 500));
        
        chart.setTitle("Biểu đồ thu/chi của khách hàng");
        plot.getDomainAxis().setTickLabelFont(new Font("Segoe UI", Font.PLAIN, 13));
        plot.getRangeAxis().setTickLabelFont(new Font("Segoe UI", Font.PLAIN, 13));
        renderer.setDefaultItemLabelsVisible(true);
        
        pnlCategory.add(chartPanel, BorderLayout.CENTER);
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCircle = new javax.swing.JPanel();
        pnlCategory = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCircle.setLayout(new java.awt.BorderLayout());

        pnlCategory.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnlCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(pnlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestChart().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCategory;
    private javax.swing.JPanel pnlCircle;
    // End of variables declaration//GEN-END:variables
}
